#!/usr/bin/env bash
## This script is work in progress, designed to be run from Cloud Shell
## Javier Cañadillas - javiercm@google.com
## ToDos:
## - Enable the script to work on Linux, Cloud Shell and Mac OS X (tooling for OS X
##   in curl -OL https://github.com/istio/istio/releases/download/1.8.1/istioctl-1.8.1-osx.tar.gz)

# Enable for script debugging
#set -x

# Defaults and unmutable vars
PLATFORM=linux-amd64
PROJECT_ID=${PROJECT_ID:-$(gcloud config get-value project 2>/dev/null)}
CLUSTER_ZONE=europe-west1-b
CLUSTER_NAME=gke-asm
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)
readonly ISTIO_VER=1.8.1
readonly ASM_SUBVER=5
readonly __SCRIPT_NAME="${0##*/}"
readonly __SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
readonly __ASM_VER_STRING=${ISTIO_VER}-asm.${ASM_SUBVER}
readonly __ASM_PACKAGE_NAME=istio-${__ASM_VER_STRING}
readonly __ASM_DOWNLOAD_URL="https://storage.googleapis.com/gke-release/asm/${__ASM_PACKAGE_NAME}-${PLATFORM}.tar.gz"
readonly GCP_ACCOUNT=$(gcloud config get-value account 2>/dev/null)


config::update_vars() {
  readonly __PROJECT_NUMBER=$(gcloud projects describe "${PROJECT_ID}" \
  --format="value(projectNumber)" 2>/dev/null)
  readonly __MEMBERSHIP_NAME=${CLUSTER_NAME}-connect
}

info() {
  echo "${green}${__SCRIPT_NAME}${reset}: ${1}" >&2
}

config::pwd_script_dir() {
  info "Setting working directory at ${__SCRIPT_DIR}"
  pushd "${__SCRIPT_DIR}" > /dev/null || return
}

config::enable_apis() {
  info "Enabling necessary GCP APIs"
  gcloud services enable \
      container.googleapis.com \
      compute.googleapis.com \
      monitoring.googleapis.com \
      logging.googleapis.com \
      cloudtrace.googleapis.com \
      meshca.googleapis.com \
      meshtelemetry.googleapis.com \
      meshconfig.googleapis.com \
      iamcredentials.googleapis.com \
      anthos.googleapis.com \
      gkeconnect.googleapis.com \
      gkehub.googleapis.com \
      cloudresourcemanager.googleapis.com \
      privateca.googleapis.com
}

config:install_packages() {
  info "Installing siege a a stress tool for the cluster"
  sudo apt -y install siege
}

gke::create_cluster() {
  info "Creating cluster ${CLUSTER_NAME} in zone ${CLUSTER_ZONE}"
  gcloud config set compute/zone ${CLUSTER_ZONE}
  gcloud beta container clusters create ${CLUSTER_NAME} \
      --machine-type=n1-standard-4 \
      --num-nodes=4 \
      --enable-stackdriver-kubernetes \
      --subnetwork=default \
      --release-channel=regular
}

gke::update_labels() {
  info "Updating GKE cluster ${CLUSTER_NAME} with necessary labels"
  gcloud container clusters update $CLUSTER_NAME \
    --update-labels \
    mesh_id=proj-"${__PROJECT_NUMBER}",asmv="${__ASMV}"
}

gke::enable_workload_identity() {
  info "Enabling workload identity in GKE cluster ${CLUSTER_NAME}"
  gcloud container clusters update ${CLUSTER_NAME} \
  --workload-pool="${PROJECT_ID}".svc.id.goog
}

gke::register_to_environ() {
  info "Registering GKE cluster ${CLUSTER_NAME} to the environ"
  gcloud beta container hub memberships register ${__MEMBERSHIP_NAME} \
    --gke-cluster=${CLUSTER_ZONE}/${CLUSTER_NAME} \
    --enable-workload-identity
}

gke::become_cluster_admin() {
  info "Making your account ${GCP_ACCOUNT} cluster admin"
  kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole cluster-admin \
    --user "${GCP_ACCOUNT}"
}

asm::download_script() {
  info "Downloading script for ASM ${__ASM_VER_STRING} and making it executable"
  curl https://storage.googleapis.com/csm-artifacts/asm/install_asm_1.8 > install_asm
  chmod +x install_asm
}

asm::validate() {
  info "Validating ASM installation requirements for cluster ${CLUSTER_NAME}"
  "${__SCRIPT_DIR}"/install_asm \
    --project_id "${PROJECT_ID}" \
    --cluster_name "${CLUSTER_NAME}" \
    --cluster_location "${CLUSTER_ZONE}" \
    --mode install \
    --output_dir "${__SCRIPT_DIR}" \
    --only_validate
}

asm::install() {
  info "Installing ASM on cluster ${CLUSTER_NAME}"
  "${__SCRIPT_DIR}"/install_asm \
    --project_id "${PROJECT_ID}" \
    --cluster_name "${CLUSTER_NAME}" \
    --cluster_location "${CLUSTER_ZONE}" \
    --mode install \
    --output_dir "${__SCRIPT_DIR}" \
    --enable_all
}

asm::enable_injection() {
  info "Enabling sidecar injection for the mesh"
  kubectl label namespace default istio-injection- istio.io/rev="${__ASMV}" --overwrite
}

app::deploy() {
  pushd ${__ASM_PACKAGE_NAME} || return >/dev/null
  info "Deploying Bookinfo application pods in cluster ${CLUSTER_NAME}"
  kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
  info "Configuring Istio Ingress Gateway for the application"
  kubectl apply -f samples/bookinfo/networking/bookinfo-gateway.yaml
}

app:check_deployment() {
  info "Checking for Bookinfo application pods readiness:"
  # Wait for deployements to be ready
  kubectl wait --for=condition=available --timeout=60s --all deployments
  info "Getting default namespace deployed services:"
  kubectl get services
  info "Getting default namespace deployed pods:"
  kubectl get pods
  info "Making sure pod \"ratings\" is available before connecting to it"
  kubectl wait --for=condition=ready pod -l app=ratings --timeout=60s
  info "Testing connectivity from pod \"ratings\" to productpage, you should get an HTML title tag."
  kubectl exec -it "$(kubectl get pod -l app=ratings \
    -o jsonpath='{.items[0].metadata.name}')" \
    -c ratings -- curl productpage:9080/productpage | grep -o  "<title>.*</title>"
  echo
}

app:get_gateway_ip() {
  info "Getting the ASM Ingress Gateway IP address"
  # Loop until the load balancer is up and running
  while [ -z "${GATEWAY_IP}" ]; do
      GATEWAY_IP=$(kubectl get svc istio-ingressgateway -o=jsonpath='{.status.loadBalancer.ingress[0].ip}' -n istio-system)
      sleep 1
  done
  info "Load Balancer IP is ${GATEWAY_IP}"
}

main::install() {
  config::pwd_script_dir
  config::enable_apis
  gke::create_cluster
  gke::update_labels
  gke::enable_workload_identity
  gke::register_to_environ
  gke::become_cluster_admin
  asm::download_script
  asm::validate
  asm::install
  asm::enable_injection
  app::deploy
  app:check_deployment
  app:get_gateway_ip
}

main::destroy() {
  info "Destroying cluster ${CLUSTER_NAME} and associated configuration and installation objects"
  config::pwd_script_dir
  # Remove cluster
  gcloud container clusters delete "${CLUSTER_NAME}" --zone "${CLUSTER_ZONE}" --quiet

  # Unregister cluster from Hub
  gcloud container hub memberships delete "${__MEMBERSHIP_NAME}" --quiet

  # Delete local files
  rm -rf "${__SCRIPT_DIR:?}/${__ASM_PACKAGE_NAME}" 2>/dev/null
  rm -rf "${__SCRIPT_DIR:?}/asm" 2>/dev/null
  rm -- *-manifest-*.yaml 2>/dev/null
  rm install_asm 2>/dev/null
}

main:get_asm_package() {
  info "Downloading ASM ${__ASM_VER_STRING}"
  curl -LO ${__ASM_DOWNLOAD_URL}
  tar xzf ${__ASM_PACKAGE_NAME}-${PLATFORM}.tar.gz
}

main::show_config() {
  cat << EOF
This is the configuration to be applied when running ${__SCRIPT_NAME}:
Platform: ${PLATFORM}
Google Cloud Project: ${PROJECT_ID}
GCP account: ${GCP_ACCOUNT}
Cluster Name: ${CLUSTER_NAME}
Region/Zone: ${CLUSTER_ZONE}
ASM Version: ${__ASM_VER_STRING}
Istio Output Directory: ${__SCRIPT_DIR}
EOF
}

main::usage() {
  cat << EOF
Usage: ${__SCRIPT_NAME} [COMMAND] [OPTIONs]...
Creates/destroys GKE cluster on GCP with ASM deployed in it.

COMMAND:
  install                           Installs the GKE cluster, ASM and deploys
                                    Bookinfo application
  destroy                           Destroys all created infrastructure,
                                    cleaning up the project
  get-asm-package                   Gets ASM package (including samples). Not
                                    necessary if you've performed an install.                                  
  show-config                       Outputs configuration used by the script

OPTIONS:
  -p|--project-id <PROJECT ID>      GCP project ID where the services will
                                    be deployed
  -c|--cluster-name <CLUSTER NAME>  Name of the GKE cluster
  -z|--cluster-zone <CLUSTER ZONE>  Location of the GKE cluster

FLAGS:
  -h                                Shows this help text

EXAMPLES:
The following invocation installs GKE, ASM and deploys bookinfo:
  $> ${__SCRIPT_NAME} install
EOF
}

# This function checks <command -option|--option argument>
# If no argument is supplied, it fails
arg_required() {
  if [[ ! "${2:-}" || "${2:0:1}" = '-' ]]; then
    echo "Option ${1} requires an argument."
  fi
}

parse_command() {
  # shellcheck disable=SC2064
  trap "$(shopt -p nocasematch)" RETURN
  shopt -s nocasematch

  case "${1}" in
  install)
    if [ -z "${PROJECT_ID}" ]; then
      echo "${red}Error${reset}: you must set a GCP project. Try doing \'gcloud config set project <projectname>\' before running the script."
    else
      main::install
    fi
    ;;
  destroy | uninstall | remove)
    main::destroy
    ;;
  get-asm-package | get_asm_package | gip)
    main:get_asm_package
    ;;
  show-config | show_config)
    main::show_config
    ;;
  *) #Catch empty or not listed command
    if [ -z "${1}" ]; then
      echo "Error: command not supplied, try again."
    else
      echo "Error: invalid command \"${1}\""
      echo ""
      main::usage
    fi
    ;;
  esac
  exit
}

parse_args() {
  # shellcheck disable=SC2064
  trap "$(shopt -p nocasematch)" RETURN
  shopt -s nocasematch

  while [[ $# != 0 ]]; do
    case "${1}" in
    -p | --project_id)
      arg_required "${@}"
      PROJECT_ID="${2}"
      shift 2
      ;;
    -c | --cluster_name | --cluster-name)
      arg_required "${@}"
      CLUSTER_NAME="${2}"
      shift 2
      ;;
    -z | --cluster_zone | --cluster-zone)
      arg_required "${@}"
      CLUSTER_ZONE="${2}"
      shift 2
      ;;
    -h | --help)
      main::usage
      exit
      ;;
    --* | -*=)
      echo "Error: unsupported flag ${1}" >&2
      exit 1
      ;;
    *)
      PARAMS+=("${1}")
      shift
      ;;
    esac
  done
}

main() {
  parse_args "${@}"
  config::update_vars
  parse_command "${PARAMS[*]}"
}

main "${@}"
